Add a record to the custom_domains table to handle routing

diff --git a/scripts/add-letsencrypt-cert b/scripts/add-letsencrypt-cert
--- a/scripts/add-letsencrypt-cert
+++ b/scripts/add-letsencrypt-cert
@@ -10,8 +10,8 @@ HELP="$(cat <<EOF
 Usage: $0 DOMAIN
 
 Sets up DOMAIN with a letsencrypt cert - note, you must have CNAME'd domain ->
-<some_canvas>.darkcustomdomain.com. Check this with 'dig domain', as Let's
-Encrypt can't verify ownership of the domain without the CNAME in place!
+<some_canvas>.darkcustomdomain.com. We'll confirm (using dig) that the CNAME is
+in place, and extract the desired canvas name from it.
 EOF
 )"
 
@@ -32,6 +32,23 @@ elif [[ "${dig_cname}" == "" ]]; then
     exit 1
 else
     echo "Expected a <something>.darkcustomdomain.com. CNAME, but got ${dig_cname}, can't continue until this is fixed."
+    exit 1
+fi
+
+CANVAS=${dig_cname//\.darkcustomdomain.com/}
+
+echo "Adding (host,canvas)=(${DOMAIN},${CANVAS}) to custom_domains to configure routing..."
+# This tmpfile crap is because for some reason gcp-psql hangs when put into a
+# subshell ( foo=$(... | ./scripts/gcp-psql) ) or when its output is piped to
+# another command (... | ./scripts/gcp-psql | grep ...)
+tmpfile=$(mktemp /tmp/custom_domain.XXXXXX)
+insert_query="INSERT INTO custom_domains (host, canvas) VALUES ('${DOMAIN}', '${CANVAS}')"
+echo "\\copy (${insert_query}) returning (host, canvas) TO ${tmpfile}" \
+    | ./scripts/gcp-psql
+if ( grep . < "${tmpfile}" > /dev/null ); then
+    echo "Added (${DOMAIN}, ${CANVAS}) to custom_domains table."
+else
+    echo "Failed to add (${DOMAIN}, ${CANVAS}) to custom_domains table - possibly there's already an entry for ${DOMAIN}?"
     exit 1
 fi
 
