Address the BadConfig case
If you manage to double-patch the darkcustomdomain-l4-ingress, you will
see this in the event log:
```
 Warning  BadConfig          9s                 cert-manager              Duplicate TLS entry for secretName "dark-002.metaforgotten.org-tls"
```

This does not break existing certs, but it does prevent further certs
from being created. I've added some checks to reduce the odds of this
happening, and also documented steps for fixing if we do end up in that
situation.

diff --git a/scripts/add-custom-domain b/scripts/add-custom-domain
--- a/scripts/add-custom-domain
+++ b/scripts/add-custom-domain
@@ -87,12 +87,33 @@ PATCH=$(cat <<-PATCH
 PATCH
 )
 
-# DANGER HERE - running this twice will make k8s sad: Warning  BadConfig          9s                 cert-manager              Duplicate TLS entry for secretName "dark-002.metaforgotten.org-tls"
+# DANGER HERE - running the patch twice will make k8s sad: Warning  BadConfig          9s                 cert-manager              Duplicate TLS entry for secretName "dark-002.metaforgotten.org-tls"
+#
+# If that happens, cert-manager can't issue more certs until it's fixed!
+#
+# This is an attempt to avoid that (though blocking dupe entries in the DB, as
+# above, will also help). However, if you find yourself in this situation,
+# here's how you can fix it manually.
+#
+# Note: I am _not_ suggesting using `kubectl patch` for this, it is hard to
+# control ("delete the nth entry in the spec.tls array" risks race conditions).
+#
+# So we may as well do it the easy way:
+# kubectl get ingress darkcustomdomain-l4-ingress -o yaml > tmp.yaml
+# Edit tmp.yaml to remove the duplicate objects from both spec.rules and
+# spec.tls
+# kubectl diff -f tmp.yaml # check that the diff is what you expect
+# kubectl apply -f tmp.yaml
+#
+# Note: if changes have been made between `kubectl get` and `kubectl apply`, you
+# WILL LOSE THOSE CHANGES. So exercise caution. `kubectl diff` helps reduce the
+# window of exposure but does not eliminate it.
+if ( kubectl get ingress darkcustomdomain-l4-ingress -o json | jq ".spec.tls[] | select(.hosts[0] == \"${DOMAIN}\")" | grep . ); then
+    echo "Can't continue - you already have a TLS cert for this domain."
+    exit 1
+fi
 
-# TODO ismith to check if this breaks anything; it may not. If not, we should at
-# least figure out if we can have a cleanup script of some kind?
 kubectl patch ingress darkcustomdomain-l4-ingress --type=json -p "${PATCH}"
-
 
 echo "Waiting for cert to become ready - we'll wait up to 60s, if this goes
 beyond that, something is probably wrong, check events in kubernetes for the
