MAke errors appear when the script is called from other scripts

diff --git a/scripts/custom-domain-get-canvas b/scripts/custom-domain-get-canvas
--- a/scripts/custom-domain-get-canvas
+++ b/scripts/custom-domain-get-canvas
@@ -16,7 +16,7 @@ EOF
 )"
 
 if [[ $# -ne 1 || "$1" == '--help' ]]; then
-    echo "$HELP"
+    echo >&2 "$HELP"
     exit 1
 fi
 
@@ -30,7 +30,7 @@ elif [[ "${dig_cname}" == "" ]]; then
   echo >&2 "No CNAME found for ${DOMAIN}"
   exit 1
 else
-  echo "Expected a <something>.darkcustomdomain.com. CNAME, but got ${dig_cname}, can't continue until this is fixed."
+  echo >&2 "Expected a <something>.darkcustomdomain.com CNAME, but got ${dig_cname}, can't continue until this is fixed."
   exit 1
 fi
 
