Check that we have versions for the containers

diff --git a/scripts/gke-deploy b/scripts/gke-deploy
--- a/scripts/gke-deploy
+++ b/scripts/gke-deploy
@@ -122,27 +122,40 @@ fi
 #########################
 if [[ ! -v SERVER_IMAGE_ID ]]; then
   SERVER_IMAGE_ID="$(docker images $GCR/${PREFIX}gcp-server -q | head -n 1)"
+  echo "SERVER_IMAGE_ID: $SERVER_IMAGE_ID"
 fi
 if [[ ! -v QW_IMAGE_ID ]]; then
   QW_IMAGE_ID="$(docker images $GCR/${PREFIX}gcp-queueworker -q | head -n 1)"
+  echo "QW_IMAGE_ID: $QW_IMAGE_ID"
 fi
 if [[ ! -v CRON_IMAGE_ID ]]; then
   CRON_IMAGE_ID="$(docker images $GCR/${PREFIX}gcp-cronchecker -q | head -n 1)"
+  echo "CRON_IMAGE_ID: $CRON_IMAGE_ID"
 fi
 if [[ ! -v GARBAGE_COLLECTOR_IMAGE_ID ]]; then
   GARBAGE_COLLECTOR_IMAGE_ID="$(docker images $GCR/${PREFIX}gcp-garbagecollector -q | head -n 1)"
+  echo "GARBAGE_COLLECTOR_IMAGE_ID: $GARBAGE_COLLECTOR_IMAGE_ID"
 fi
 if [[ ! -v STROLLER_IMAGE_ID ]]; then
   STROLLER_IMAGE_ID="$(docker images $GCR/${PREFIX}stroller -q | head -n 1)"
+  echo "STROLLER_IMAGE_ID: $STROLLER_IMAGE_ID"
 fi
 if [[ ! -v QUEUE_SCHEDULER_IMAGE_ID ]]; then
   QUEUE_SCHEDULER_IMAGE_ID="$(docker images $GCR/${PREFIX}queue-scheduler -q | head -n 1)"
+  echo "QUEUE_SCHEDULER_IMAGE_ID: $QUEUE_SCHEDULER_IMAGE_ID"
 fi
 if [[ ! -v TUNNEL_IMAGE_ID ]]; then
   TUNNEL_IMAGE_ID="$(docker images $GCR/${PREFIX}tunnel -q | head -n 1)"
+  echo "TUNNEL_IMAGE_ID: $TUNNEL_IMAGE_ID"
 fi
 if [[ ! -v POSTGRES_HONEYTAIL_IMAGE_ID ]]; then
   POSTGRES_HONEYTAIL_IMAGE_ID="$(docker images $GCR/${PREFIX}postgres-honeytail -q | head -n 1)"
+  echo "POSTGRES_HONEYTAIL_IMAGE_ID: $POSTGRES_HONEYTAIL_IMAGE_ID"
+fi
+
+if [[ "$SERVER_IMAGE_ID" == "" || "$QW_IMAGE_ID" == "" || "$CRON_IMAGE_ID" == "" || "$GARBAGE_COLLECTOR_IMAGE_ID" == "" || "$STROLLER_IMAGE_ID" == "" || "$QUEUE_SCHEDULER_IMAGE_ID" == "" || "$TUNNEL_IMAGE_ID" == "" || "$POSTGRES_HONEYTAIL_IMAGE_ID" == "" ]]; then
+  echo "Missing image IDs"
+  exit 1
 fi
 
 CHANGE_CAUSE="circle=${CIRCLE_BUILD_URL} ; orig-time: $(date); git-commit: $(git rev-parse --short HEAD)"
