Add gcp-create-db and call it from create-cluster

diff --git a/scripts/gke-create-cluster b/scripts/gke-create-cluster
--- a/scripts/gke-create-cluster
+++ b/scripts/gke-create-cluster
@@ -77,6 +77,7 @@ Other Options:
                          amount (default $DARK_CLUSTER_NUM_NODES).
   --configmap-file=...   The path of the env-file the cluster config map will be created from/updated
                          to (default $DARK_CLUSTER_CONFIGMAP_FILE)
+  --with-new-database    Also create new CloudSQL Postgres instance and wire it up
   --version=...          The Kubernetes version to run on the master and nodes. New versions are
                          released and old versions are obsoleted on GKE quickly, so you will
                          probably need to find the newest version (default $DARK_CLUSTER_VERSION).
@@ -131,6 +132,9 @@ do
     --assets-creds=*)
       DARK_CLUSTER_STATIC_ASSETS_CREDS="${i/--assets-creds=/''}"
       ;;
+    --with-new-database)
+      WITH_NEW_DATABASE="true"
+      ;;
     --help)
       echo "$HELP"
       exit 0
@@ -146,6 +150,19 @@ done
 function print_step () {
   tput setab 6 && echo "=>" "$@" && tput sgr0
 }
+
+if [ -v WITH_NEW_DATABASE ] && [[ "${WITH_NEW_DATABASE}" == "true" ]]; then
+  # currently we use the default user
+  DARK_CLUSTER_CLOUDSQL_USER="postgres"
+  if [ ! -v DARK_CLUSTER_CLOUDSQL_PASS ]; then
+    echo "When creating a new database with a cluster, --cloudsql-pass is required"
+    exit 1
+  fi
+  ./scripts/gcp-create-db \
+    --region=$DARK_CLUSTER_REGION \
+    --cloudsql-instance-name=$DARK_CLUSTER \
+    --cloudsql-pass=$DARK_CLUSTER_CLOUDSQL_PASS
+fi
 
 if [ ! -v DARK_CLUSTER_BWD_TLS_KEY ] || [ ! -v DARK_CLUSTER_BWD_TLS_CRT ] \
      || [ ! -v DARK_CLUSTER_DL_TLS_KEY ] || [ ! -v DARK_CLUSTER_DL_TLS_CRT ] \
