Do better at killing processes

diff --git a/scripts/build/_dotnet-wrapper b/scripts/build/_dotnet-wrapper
--- a/scripts/build/_dotnet-wrapper
+++ b/scripts/build/_dotnet-wrapper
@@ -12,11 +12,11 @@ shopt -s lastpipe
 cd fsharp-backend && unbuffer dotnet "$@" 2>&1 | while read -r line; do
   # this error consistently breaks our compile in the build script
   if [[ "$line" == *"warning MSB3026: Could not copy "* ]]; then
-    "Saw a failed copy, killing servers"
-    killall ApiServer
-    killall ApiServer2
-    killall BwdServer
-    killall BwdServer2
+    echo "Saw a failed copy, killing servers"
+    killall ApiServer || true
+    killall BwdServer || true
+    killall CronChecker || true
+    killall QueueWorker || true
   fi
-  echo "$line";
+  echo "$line"
 done
